config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'

  resources :favorites, only: [:create, :destroy]
  resources :microposts, only: [:create, :destroy, :new]
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: t("dictionary.messages.micropost") %>
    </div>
    <%= f.submit t("dictionary.actions.post"), class: "btn, btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(user, size: 50), user %>
<% if current_user?(user) %>
    <h1><%= link_to user.name, user %></h1>
<% else %>
    <h1><%= user.name %></h1>
<% end %>
<div>
    <span class="glyphicon glyphicon-bookmark">
        <%= link_to user.url.to_s, user.url %>
    </span>
    <br>
    <span class="glyphicon glyphicon-map-marker">
        <%= user.region %>
    </span>
    <br>
    <span>
        <%= user.description %>
    </span>
    <br>
</div>
<div>
    <span>
        <%= pluralize(user.microposts.count, "micropost") %>, 
        <%= link_to pluralize(user.favorite_microposts.count, "favorite"), favorites_user_path(user.id) %>
    </span>
    <span>
        <%= link_to pluralize(user.follower_users.count, 'follower'), followers_user_path(user.id) %>,
        <%= link_to pluralize(user.following_users.count, 'following'), followings_user_path(user.id) %>
    </span>
</div>