config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'

  resources :favorites, only: [:create, :destroy]
  resources :microposts, only: [:create, :destroy, :new]
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('home'),   root_path %></li>
        <li><%= link_to t('help'),   '#' %></li>
        <% if logged_in? %>
          <li><%= link_to t('user'), '#' %></li>
          <li class="dropdown">
            <a href='#' class="dropdown-toggle" data-toggle="dropdown">
              <%= t('account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('profile'), current_user %></li>
              <li><%= link_to t('settings'), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('logout'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('login'), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>